name: manim
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blosc=1.21.6=hfd34d9b_1
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py313h5813708_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.4.26=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - cartopy=0.24.0=py313hf91d08e_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py313ha7868ed_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h1ec8472_0
  - cpython=3.13.3=py313hd8ed1ab_101
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.14=py313h5813708_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - folium=0.19.5=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py313hb4c8b1a_0
  - freetype=2.13.3=h57928b3_1
  - freexl=2.0.0=hf297d47_2
  - geopandas=1.0.1=pyhd8ed1ab_3
  - geopandas-base=1.0.1=pyha770c72_3
  - geos=3.13.1=h9ea8674_0
  - geotiff=1.7.4=h86c3423_2
  - graphite2=1.3.13=h63175ca_1003
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.1.0=h8796e6f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=9.2.0=pyhca29cf9_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - kiwisolver=1.4.7=py313h1ec8472_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.7.7=h5343c79_4
  - libblas=3.9.0=31_h641d27c_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=31_h5e41251_mkl
  - libclang13=20.1.4=default_h6e92b77_0
  - libcurl=8.13.0=h88aaa65_0
  - libdeflate=1.23=h76ddb4d_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=14.2.0=h1383e82_2
  - libgdal-core=3.10.3=h36da5af_5
  - libglib=2.84.1=h7025463_0
  - libgomp=14.2.0=h1383e82_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=31_h1aa476e_mkl
  - liblzma=5.8.1=h2466b09_0
  - libmpdec=4.0.0=h2466b09_0
  - libpng=1.6.47=h7a4582a_0
  - librttopo=1.1.0=hbfc9ebc_18
  - libsodium=1.0.20=hc70643c_0
  - libspatialite=5.1.0=h378fb81_14
  - libsqlite=3.49.1=h67fdade_2
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=h797046b_4
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.7=h442d1da_1
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=hcfcfb64_1001
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.2=py313hb4c8b1a_1
  - matplotlib=3.10.1=py313hfa70ccb_0
  - matplotlib-base=3.10.1=py313h81b4f16_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2024.2.2=h66d3029_15
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.5=py313hefb8edb_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py313hf91d08e_3
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=h99c9b8b_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py313hda88b71_0
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.0=had0cd8c_0
  - proj=9.6.0=h4f671f6_1
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py313ha7868ed_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyogrio=0.10.0=py313h75b81ac_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py313hc3e4018_1
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pyside6=6.9.0=py313hb43cee3_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.13.3=h261c0b1_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=26.4.0=py313h2100fd5_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.0=h83cda92_1
  - requests=2.32.3=pyhd8ed1ab_1
  - scikit-learn=1.6.1=py313h4f67946_0
  - scipy=1.15.2=py313h2eca4b9_0
  - setuptools=80.1.0=pyhff2d567_0
  - shapely=2.1.0=py313h410098b_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - sqlite=3.49.1=h2466b09_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=h62715c5_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.2=py313ha7868ed_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xarray=2025.4.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.22.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.23.0=py313ha7868ed_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.6
      - aiosignal==1.3.2
      - attrs==25.3.0
      - audioop-lts==0.2.1
      - av==13.1.0
      - beautifulsoup4==4.13.4
      - click==8.1.8
      - cloudpickle==3.1.1
      - cloup==3.0.7
      - crc32c==2.7.1
      - dask==2025.5.1
      - donfig==0.8.1.post1
      - fastjsonschema==2.21.1
      - frozenlist==1.6.0
      - fsspec==2025.5.1
      - glcontext==3.0.0
      - isosurfaces==0.1.2
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - locket==1.0.0
      - manim==0.19.0
      - manimpango==0.6.0
      - mapbox-earcut==1.0.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - moderngl==5.12.0
      - moderngl-window==3.1.1
      - multidict==6.4.4
      - nbformat==5.10.4
      - numcodecs==0.16.1
      - partd==1.4.2
      - pigar==2.1.7
      - platformdirs==4.3.8
      - propcache==0.3.1
      - pycairo==1.28.0
      - pydub==0.25.1
      - pyglet==2.1.6
      - pyglm==2.8.2
      - pywin32==310
      - pyyaml==6.0.2
      - referencing==0.36.2
      - rich==14.0.0
      - rpds-py==0.25.1
      - screeninfo==0.8.1
      - skia-pathops==0.8.0.post2
      - soupsieve==2.7
      - srt==3.5.3
      - svgelements==1.9.6
      - toolz==1.0.0
      - watchdog==6.0.0
      - yarl==1.20.0
      - zarr==3.0.8
prefix: C:\Users\Emanuel\Miniconda3\envs\manim
